### PR TITLE
Libraryfication

### PR DESCRIPTION
**Pull request by cecton**
Hello :wave: 

I think it would be nice to have this available as a library as other CLI tools would benefit from it.

Let me know your thoughts

### CODE REVIEW

**Comment by cecton** [comment]
@Kestrer I didn't touch the code at all. I only moved stuff

**Comment by Kestrer** [comment]
Thanks for doing this! I'm going to clean up the API a bit and then hopefully make a release :)

**Comment by Kestrer** [comment]
Wait actually, this doesn't need to be a library. I just remembered that [`textwrap`](https://docs.rs/textwrap) exists, I don't _think_ this API would offer any additional functionality. Could you use that instead?

**Comment by cecton** [comment]
Yours take colors into account

**Comment by Kestrer** [comment]
I don't think it does, but [`textwrap` seems to](https://github.com/mgeisler/textwrap/blob/master/src/core.rs#L49).

**Comment by cecton** [comment]
I will check later as I'm not at home right now

**Comment by cecton** [comment]
Hey sorry for the late reply.

It is complicated... I personally thought that Rust's textwrap was exactly the same than Python's textwrap: re-working paragraph. So for example in Python, newlines can be removed from the original input:

```
Python 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textwrap
>>> textwrap.fill("Hello\nWorld", 80)
'Hello World'
>>> 
```

But I tested that on playground and it didn't behave the same: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=170d0d076da7248f5cc569dc02f4df24

The way I saw it:
- textwrap should be a tool that ignores terminal escape codes (because it can be used outside terminals)
- it re-works paragraphs, possibly joining lines

In reality though:
- Rust's text wrap has the capability to take the terminal escape codes into account (I have no idea if the Python one does have an option for that)
- it doesn't remove existing new lines

So I think you're right. I don't really need your variant of textwrap.

**Pull request merged**
